# Generated by Django 3.1.2 on 2021-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('year_of_construction', models.IntegerField(max_length=30)),
                ('year_of_renovation', models.IntegerField(max_length=30)),
                ('total_prince', models.IntegerField(max_length=30)),
                ('total_area', models.IntegerField(max_length=30)),
                ('price_m', models.IntegerField(max_length=30)),
                ('has_elevator', models.BooleanField()),
                ('valuation_date', models.DateField()),
            ],
        ),
    ]
